# Generated by Django 4.2.7 on 2024-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, default='default/default-user.jpg', null=True, upload_to='logo/users'),
        ),
    ]
